databases:
  - name: api
    plan: free
    databaseName: backend
    user: siamliam12

services:
  - type: web
    plan: free
    name: api
    runtime: python
    buildCommand: "./backend/build.sh"
    startCommand: "python -m gunicorn ./backend/api.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4