databases:
  - name: api
    plan: free
    databaseName: bakend
    user: siamliam12

services:
  - type: web
    plan: free
    name: api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4